/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rwth_i2_ltl2ba4j_internal_jnibridge_BAJni */

#ifndef _Included_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
#define _Included_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_init
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    setform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_setform
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    tl_parse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_tl_1parse
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    bstates
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_bstates
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    b_accept
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_b_1accept
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    print_buchi
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_print_1buchi
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    get_sym_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_get_1sym_1id
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    get_sym_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_get_1sym_1size
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    get_sym_table
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_get_1sym_1table
  (JNIEnv *, jobject);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    bstateNxt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_bstateNxt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    bstateFinal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_bstateFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    bstateId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_bstateId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    bstateFirstTrans
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_bstateFirstTrans
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    btransNxt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_btransNxt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    btransTo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_btransTo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    btransPos
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_btransPos
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rwth_i2_ltl2ba4j_internal_jnibridge_BAJni
 * Method:    btransNeg
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rwth_i2_ltl2ba4j_internal_jnibridge_BAJni_btransNeg
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
